services:
  # Database
  mongo-db:
    image: mongo:4.4
    command: --nojournal

  # Context Broker
  orion:
    image: fiware/orion-ld:1.1.0
    depends_on:
      - mongo-db
      - timescale-db
    ports:
      - 1026:1026 # localhost:1026
    environment:
      - ORIONLD_TROE=TRUE
      - ORIONLD_TROE_USER=orion
      - ORIONLD_TROE_PWD=orion
      - ORIONLD_TROE_HOST=timescale-db
      - ORIONLD_MONGO_HOST=mongo-db
      - ORIONLD_MULTI_SERVICE=TRUE
      - ORIONLD_DISABLE_FILE_LOG=TRUE
    command: -dbhost mongo-db -logLevel ERROR -troePoolSize 10 -forwarding 
    healthcheck:
      test: curl --fail -s http://orion:1026/version || exit 1
      interval: 5s

  mintaka:
    image: fiware/mintaka:0.5.35
    depends_on:
      timescale-db:
        condition: service_healthy
    environment:
      - DATASOURCES_DEFAULT_HOST=timescale-db
      - DATASOURCES_DEFAULT_PORT=5432
      - DATASOURCES_DEFAULT_USERNAME=orion
      - DATASOURCES_DEFAULT_PASSWORD=orion
      - DATASOURCES_DEFAULT_DATABASE=orion
      - DATASOURCES_DEFAULT_MAXIMUM_POOL_SIZE=2
      - ENDPOINTS_INFO_ENABLED=true
      - ENDPOINTS_INFO_SENSITIVE=false
    ports:
      - 8080:8080

  timescale-db:
    image: timescale/timescaledb-postgis:1.7.5-pg12
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U orion" ]
      interval: 15s
      timeout: 15s
      retries: 5
      start_period: 60s
    environment:
      - POSTGRES_USER=orion
      - POSTGRES_PASSWORD=orion
      - POSTGRES_HOST_AUTH_METHOD=trust
    command: ["postgres", "-c", "log_statement=none"]
    ports:
      - 5435:5432

